# Generated by Django 3.2.4 on 2021-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kliniks', '0004_hari_jadwal_dokter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal_dokter',
            name='hari',
        ),
        migrations.AddField(
            model_name='jadwal_dokter',
            name='tanggal',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='hari',
        ),
    ]
