# Generated by Django 3.2.4 on 2021-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kliniks', '0005_auto_20210804_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_dokter',
            name='jam_mulai',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jadwal_dokter',
            name='jam_selesai',
            field=models.TimeField(),
        ),
    ]
