# Generated by Django 3.2.4 on 2021-08-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kliniks', '0007_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal_dokter',
            name='hari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kliniks.hari'),
        ),
    ]
