# Generated by Django 3.2.4 on 2021-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kliniks', '0008_jadwal_dokter_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='hari',
            name='nama_indo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hari',
            name='nama',
            field=models.CharField(max_length=15),
        ),
    ]
