# Generated by Django 3.2.4 on 2021-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kliniks', '0009_auto_20210804_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hari',
            name='nama_indo',
            field=models.CharField(max_length=6),
        ),
    ]
